f=open('GW_THE/chapter7.html','r',encoding='utf-8')
html=f.read()
f.close()
print('LEN', len(html))
print('A', html.find('Step-drawdown test separates'))
print('B', html.find('Five key screen'))
print('C', html.find('Gravel pack design'))
print('D', html.find('Infiltration gallery yield'))
print('E', html.find('Well development methods'))
